version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"  # Exposing port 8080 to access via browser
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx config file
      - ./app/public:/var/www/public  # Mount your Laravel public directory
    depends_on:
      - php
      - mysql  # Ensure MySQL starts before Nginx
    networks:
      - app-network

  php:
    image: php:8.2-fpm
    container_name: php
    volumes:
      - ./app:/var/www  # Mount your Laravel app files
    depends_on:
      - mysql  # Ensure PHP waits for MySQL
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - "3306:3306"  # MySQL port
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent storage
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"  # phpMyAdmin available at http://localhost:8081
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: P@ssw0rd
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge


# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: laravel_app
#     restart: always
#     working_dir: /var/www
#     volumes:
#       - .:/var/www
#     depends_on:
#       - db
#     networks:
#       - laravel_network

#   nginx:
#     image: nginx:latest
#     container_name: laravel_nginx
#     restart: always
#     ports:
#       - "8080:80"
#     volumes:
#       - .:/var/www
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - app
#     networks:
#       - laravel_network

#   db:
#     image: mysql:8
#     container_name: laravel_db
#     restart: always
#     environment:
#       MYSQL_DATABASE: laravel
#       MYSQL_ROOT_PASSWORD: P@ssw0rd
#       MYSQL_USER: laraveluser
#       MYSQL_PASSWORD: laravelpassword
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - laravel_network

# networks:
#   laravel_network:
#     driver: bridge

# volumes:
#   mysql_data:
